version: '3.8'

services:
  db:
    image: postgres:16
    container_name: codeguard_db
    environment:
      - POSTGRES_DB=codeguard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: codeguard_redis
    ports:
      - "6379:6379"

  execution_arena_image:
    build:
      context: .
      dockerfile: docker/execution-arena-java/Dockerfile
    image: codeguard-arena-java:latest
    profiles: ["build-only"]
    command: ["sh", "-c", "echo arena image built"]

volumes:
  postgres_data: