server:
  port: 8080

spring:
  application:
    name: codeguard


  datasource:
    url: jdbc:postgresql://localhost:5432/codeguard
    username: postgres
    password: Pass123
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Это заставит Hibernate использовать правильные типы Postgres (например, TEXT)
        dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    enabled: false


  data:
    redis:
      host: localhost
      port: 6379


application:
  security:
    jwt:
      secret-key: "q52HnyQniFXrzzITVFBjFrZASQ6JtxmFVwHDVDCbCzo="
      expiration: 86400000
  execution:
    arena-image: codeguard-arena-java:latest
    cpu-set: "0"
    default-memory-mb: 128

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
#    root: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG